/** Design-review gallery types.
 *
 *  A "design review" is a structured, point-in-time audit of the production UI
 *  (generated by the `design-drift-audit` workflow). Reviews accumulate over
 *  time; the gallery at `/design` lists them newest-first and `/design/[slug]`
 *  renders one via a shared data-driven template.
 *
 *  The canonical source for each review is its JSON in the repo-root
 *  `design-reviews/` drop zone. An entry file under `./entries/` imports that
 *  JSON, attaches authored header fields, and derives gallery-card metadata via
 *  `toReviewMeta` (see `./derive-meta.ts`).
 */

export type Severity = "low" | "medium" | "high" | "critical";
export type Priority = "P1" | "P2" | "P3";
export type Effort = "XS" | "S" | "M" | "L" | "XL";

export type Finding = {
  file: string;
  line: number;
  issue: string;
  /** Offending source snippet, when the audit captured one. */
  snippet?: string;
  recommendation: string;
};

export type Dimension = {
  /** Human name of the audited dimension, e.g. "Typography ladder". */
  dimension: string;
  severity: Severity;
  summary: string;
  /** Audit's estimate of total occurrences (findings[] is a representative sample). */
  approxTotalCount: number;
  findings: Finding[];
  systemicRecommendation: string;
};

export type TopRecommendation = {
  priority: Priority;
  recommendation: string;
  rationale: string;
  /** Dimension names this recommendation addresses. */
  affectedDimensions: string[];
};

export type RemediationTask = {
  title: string;
  scope: string;
  effort: Effort;
};

export type Synthesis = {
  executiveSummary: string;
  overallHealth: string;
  healthGrade: string;
  crossCuttingThemes: string[];
  topRecommendations: TopRecommendation[];
  suggestedRemediationTasks: RemediationTask[];
};

/** The full review payload — the shape of each `design-reviews/*.json`. */
export type DesignReview = {
  generatedFor: string;
  dimensions: Dimension[];
  synthesis: Synthesis;
};

/** Authored header fields that don't live in the audit JSON. */
export type DesignReviewHeader = {
  /** URL slug + sort key, e.g. "2026-05-29-review-1". */
  slug: string;
  /** ISO date (YYYY-MM-DD) the review was generated. */
  date: string;
  reviewNumber: number;
  title: string;
  /** One-line gallery summary. Falls back to the executive summary's first sentence. */
  summary?: string;
  /** How the review was produced, e.g. workflow name + run id + agent count. */
  method: string;
};

/** Gallery-card metadata — derived from the review + authored header. */
export type DesignReviewMeta = {
  slug: string;
  date: string;
  reviewNumber: number;
  title: string;
  summary: string;
  healthGrade: string;
  method: string;
  /** Per-dimension severity + count, for the card's at-a-glance strip. */
  dimensions: { name: string; severity: Severity; count: number }[];
};

/** A registry entry: gallery metadata + the full review it renders. */
export type DesignReviewEntry = {
  meta: DesignReviewMeta;
  review: DesignReview;
};
